AWSTemplateFormatVersion: 2010-09-09
Resources:
    
  # EC2 instance which will have access for http and ssh
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
           
      SecurityGroupIds:
        - Test_Aryaman
      KeyName: KeyName
      ImageId: ami-0c1a7f89451184c8b 
      UserData: 
        Fn::Base64: |
          #!/bin/bash -xe
          sudo apt update -y 
          sudo apt install -y apache2 
          sudo systemctl start apache2 
          sudo systemctl enable apache2 
          echo "jab we met" > /var/www/html/index.html

      

# output important values for easy viewing in cloudformation dashboard
Outputs:
  InstanceId:
    Description: InstanceId of the first EC2 instance
    Value: !Ref EC2Instance

  PublicDNS:
    Description: Public DNS Name of the EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp
